<?php

namespace App\Filament\Resources\Astpp\OrderResource\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\DeleteAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class OrderTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id')->label('Id')->searchable()->sortable()->limit(40)->toggleable(),
                TextColumn::make('order.order_id')->label('Order ID')->searchable()->sortable()->toggleable(),
                TextColumn::make('account.number')->label('Accountid')->searchable()->sortable()->toggleable(),
                TextColumn::make('reseller.number')->label('Reseller ID')->searchable()->sortable()->toggleable(),
                TextColumn::make('parentOrder.order_id')->label('Parent Order ID')->searchable()->sortable()->toggleable(),
                TextColumn::make('order_date')->label('Order Date')->dateTime()->sortable()->toggleable(),
                TextColumn::make('order_generated_by')->label('Order Generated By')->searchable()->sortable()->limit(40)->toggleable(),
                TextColumn::make('payment_gateway')->label('Payment Gateway')->searchable()->sortable()->limit(40)->toggleable(),
                TextColumn::make('payment_status')->label('Payment Status')->searchable()->sortable()->limit(40)->toggleable(),
                TextColumn::make('ip')->label('IP')->searchable()->sortable()->limit(40)->toggleable(),
            ])
            ->actions([
                ViewAction::make(),
                EditAction::make(),
            ])
            ->bulkActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
